- hosts: host-name
  remote_user: lawren
  tasks:
  - name: Ensure SSH can pass the firewall
    firewalld:
      service: ssh
      state: enabled
      permanent: True
      immediate: True
    become: True

- hosts: host-ip
  remote_user: lawren
  tasks:
  - name: Ensure SSH can pass the firewall
    firewalld:
      service: ssh
      state: enabled
      permanent: True
      immediate: True
    become: True
