package cht.hioss.test.entity;

// Generated 2018/10/25 �U�� 06:18:15 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", schema = "public")
public class Department implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Person> persons = new HashSet<Person>(0);

	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, Set<Person> persons) {
		this.id = id;
		this.name = name;
		this.persons = persons;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
