package cht.hioss.test.entity;

// Generated 2018/10/25 �U�� 06:18:15 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonDetails generated by hbm2java
 */
@Entity
@Table(name = "person_details", schema = "public")
public class PersonDetails implements java.io.Serializable {

	private int id;
	private Person person;
	private String title;

	public PersonDetails() {
	}

	public PersonDetails(int id) {
		this.id = id;
	}

	public PersonDetails(int id, Person person, String title) {
		this.id = id;
		this.person = person;
		this.title = title;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "title", length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
